for(var i = 0; i < 146; i++) { var scriptId = 'u' + i; window[scriptId] = document.getElementById(scriptId); }

$axure.eventManager.pageLoad(
function (e) {

});
gv_vAlignTable['u21'] = 'top';gv_vAlignTable['u32'] = 'center';gv_vAlignTable['u7'] = 'center';gv_vAlignTable['u4'] = 'top';gv_vAlignTable['u140'] = 'center';gv_vAlignTable['u17'] = 'center';gv_vAlignTable['u135'] = 'center';gv_vAlignTable['u42'] = 'center';gv_vAlignTable['u101'] = 'center';gv_vAlignTable['u48'] = 'center';gv_vAlignTable['u27'] = 'top';gv_vAlignTable['u138'] = 'center';gv_vAlignTable['u52'] = 'center';gv_vAlignTable['u20'] = 'top';gv_vAlignTable['u67'] = 'center';gv_vAlignTable['u65'] = 'center';gv_vAlignTable['u120'] = 'top';gv_vAlignTable['u110'] = 'center';gv_vAlignTable['u108'] = 'center';gv_vAlignTable['u62'] = 'top';gv_vAlignTable['u11'] = 'center';gv_vAlignTable['u75'] = 'top';gv_vAlignTable['u133'] = 'center';gv_vAlignTable['u34'] = 'center';gv_vAlignTable['u68'] = 'top';gv_vAlignTable['u39'] = 'top';gv_vAlignTable['u72'] = 'top';gv_vAlignTable['u99'] = 'center';gv_vAlignTable['u112'] = 'center';gv_vAlignTable['u44'] = 'center';gv_vAlignTable['u78'] = 'top';gv_vAlignTable['u57'] = 'top';gv_vAlignTable['u125'] = 'center';gv_vAlignTable['u54'] = 'center';gv_vAlignTable['u118'] = 'top';gv_vAlignTable['u88'] = 'center';gv_vAlignTable['u38'] = 'center';gv_vAlignTable['u26'] = 'top';gv_vAlignTable['u23'] = 'top';gv_vAlignTable['u144'] = 'center';gv_vAlignTable['u36'] = 'center';gv_vAlignTable['u30'] = 'top';gv_vAlignTable['u95'] = 'top';gv_vAlignTable['u61'] = 'top';gv_vAlignTable['u116'] = 'center';gv_vAlignTable['u74'] = 'top';gv_vAlignTable['u123'] = 'top';gv_vAlignTable['u114'] = 'center';gv_vAlignTable['u92'] = 'center';gv_vAlignTable['u46'] = 'center';gv_vAlignTable['u71'] = 'center';gv_vAlignTable['u127'] = 'center';gv_vAlignTable['u56'] = 'center';gv_vAlignTable['u142'] = 'center';gv_vAlignTable['u106'] = 'center';gv_vAlignTable['u40'] = 'top';gv_vAlignTable['u104'] = 'center';gv_vAlignTable['u19'] = 'center';gv_vAlignTable['u84'] = 'top';gv_vAlignTable['u50'] = 'center';gv_vAlignTable['u97'] = 'top';gv_vAlignTable['u63'] = 'top';gv_vAlignTable['u76'] = 'top';gv_vAlignTable['u81'] = 'top';gv_vAlignTable['u94'] = 'top';gv_vAlignTable['u60'] = 'top';gv_vAlignTable['u102'] = 'top';gv_vAlignTable['u9'] = 'top';gv_vAlignTable['u73'] = 'top';gv_vAlignTable['u69'] = 'top';gv_vAlignTable['u131'] = 'center';gv_vAlignTable['u24'] = 'top';gv_vAlignTable['u29'] = 'center';gv_vAlignTable['u129'] = 'center';gv_vAlignTable['u86'] = 'center';gv_vAlignTable['u58'] = 'top';gv_vAlignTable['u83'] = 'center';gv_vAlignTable['u8'] = 'top';gv_vAlignTable['u3'] = 'center';gv_vAlignTable['u96'] = 'top';gv_vAlignTable['u80'] = 'center';gv_vAlignTable['u1'] = 'center';gv_vAlignTable['u93'] = 'top';gv_vAlignTable['u145'] = 'top';gv_vAlignTable['u25'] = 'top';gv_vAlignTable['u59'] = 'top';gv_vAlignTable['u90'] = 'center';gv_vAlignTable['u77'] = 'top';gv_vAlignTable['u22'] = 'top';gv_vAlignTable['u136'] = 'top';document.getElementById('u28_img').tabIndex = 0;

u28.style.cursor = 'pointer';
$axure.eventManager.click('u28', function(e) {

if (true) {

}
});
